---
- name: Check Vagrant version
  command: vagrant --version
  changed_when: no
  failed_when: no
  register: vagrant_version_result

- name: Include Vagrant installtion tasks
  become: yes
  include_tasks: install.yml
  when: vagrant_version_result.stdout | regex_search('[0-9]+\\.[0-9]+\\.[0-9]+') != vagrant_version
